### PR TITLE
param hide_shipping_untill_address_selection

### PR DESCRIPTION
**Pull request by brianteeman**
hide_shipping_untill_address_selection => hide_shipping_until_address_selection

### CODE REVIEW

**Comment by j2commerce** [comment]
Brian @brianteeman It looks like you did not intend that change

**Comment by brianteeman** [comment]
ah - gotya - double fix,. let me redo it

**Comment by j2commerce** [comment]
> should be correct now

Super, it is, thanks Brian @brianteeman !

**Comment by j2commerce** [comment]
Thanks Brian!

**Pull request merged**
