### PR TITLE
Added test on user to determine if the module should show or not

### PR DESCRIPTION
**Pull request by obuisard**

### CODE REVIEW

**Comment by brianteeman** [comment]
This is an admin menu module. How can there ever be a situation that a user is not logged in?

**Comment by obuisard** [comment]
It is to avoid this:

image

**Comment by brianteeman** [comment]
I thought that might be what you meant. Its not the correct solution and yes I see you did it this way the core guided yours module. ;)

A better way is to check if the user has permissions for j2store and only display the module then. thats how core should be doing it. something like

```
        if (
            !$this->getApplication()->getIdentity()->authorise('core.manage', 'com_j2store')
        ) {
            return;
        `}`
```

**Comment by j2commerce** [comment]
Ok, I understand, thanks Brian @brianteeman. It does cover also the case where someone should not have access to the module in the console, once logged in.

**Comment by brianteeman** [comment]
@j2commerce perfect

**Review by j2commerce — APPROVED** [review]

**Pull request merged**
